when@dev:
    web_profiler:
        toolbar: '%profiler.enabled%'
        intercept_redirects: false

    framework:
        profiler:
            enabled: '%profiler.enabled%'
            only_exceptions: '%profiler.only_exceptions%'
            collect_serializer_data: false

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
